### ISSUE TITLE
License

### ISSUE THREAD

**Issue by haesleinhuepf** [krulllab/GAP#1]
Hi @alex-krull ,

congrats to this amazing project and thanks for sharing it! Would you mind adding a license file so that others can legally reuse the code und specified conditions? I'm sure this could be useful to many people!

If you're new to licensing, check out this blog post:
https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Big thanks!

Best,
Robert

**Comment by alex-krull** [comment]
Thanks for pointing this out Robert! I didn't expect people would be interested so quickly.

**Comment by alex-krull** [comment]
This is fixed.
