### ISSUE TITLE
conda env create -f gap.yml   fails on windows

### ISSUE THREAD

**Issue by bobfRT1** [krulllab/GAP#2]
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - setuptools==63.2.0=py39hf3d152e_0
  - _openmp_mutex==4.5=2_kmp_llvm
  - cudatoolkit==11.6.0=hecad31d_10
  - libiconv==1.17=h166bdaf_0
  - ld_impl_linux-64==2.36.1=hea4e1c9_2
  - libtiff==4.4.0=hc85c160_1
  - ca-certificates==2022.6.15=ha878542_0
  - libdeflate==1.12=h166bdaf_0
  - lerc==3.0=h9c3ff4c_0
  - numpy-base==1.22.3=py39hf524024_0
  - gnutls==3.6.13=h85f3911_1
  - ffmpeg==4.3=hf484d3e_0
  - xorg-libxau==1.0.9=h7f98852_0
  - bzip2==1.0.8=h7f98852_4
  - mkl-service==2.4.0=py39h7e14d7c_0
  - openjpeg==2.4.0=hb52868f_1
  - sqlite==3.39.1=h4ff8645_0
  - mkl_fft==1.3.1=py39h0c7bc48_1
  - libnsl==2.0.0=h7f98852_0
  - mkl==2021.4.0=h8d4b97c_729
  - mkl_random==1.2.2=py39hde0f152_0
  - _libgcc_mutex==0.1=conda_forge
  - openh264==2.1.1=h780b84a_0
  - gmp==6.2.1=h58526e2_0
  - libstdcxx-ng==12.1.0=ha89aaad_16
  - cryptography==37.0.4=py39hd97740a_0
  - openssl==1.1.1q=h166bdaf_0
  - cffi==1.15.1=py39he91dace_0
  - libwebp==1.2.2=h3452ae3_0
  - pysocks==1.7.1=py39hf3d152e_5
  - zlib==1.2.12=h166bdaf_2
  - zstd==1.5.2=h8a70e8d_2
  - jpeg==9e=h166bdaf_2
  - certifi==2022.6.15=py39hf3d152e_0
  - libffi==3.4.2=h7f98852_5
  - xz==5.2.5=h516909a_1
  - nettle==3.6=he412f7d_0
  - llvm-openmp==14.0.4=he0ac6c6_0
  - pytorch==1.12.0=py3.9_cuda11.6_cudnn8.3.2_0
  - libzlib==1.2.12=h166bdaf_2
  - libpng==1.6.37=h753d276_3
  - libwebp-base==1.2.2=h7f98852_1
  - pillow==9.2.0=py39hae2aec6_0
  - libxcb==1.13=h7f98852_1004
  - lz4-c==1.9.3=h9c3ff4c_1
  - tk==8.6.12=h27826a3_0
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - libuuid==2.32.1=h7f98852_1000
  - readline==8.1.2=h0f457ee_0
  - pthread-stubs==0.4=h36c2ea0_1001
  - brotlipy==0.7.0=py39hb9d737c_1004
  - giflib==5.2.1=h36c2ea0_2
  - libgcc-ng==12.1.0=h8d9b700_16
  - numpy==1.22.3=py39he7a7128_0
  - lame==3.100=h7f98852_1001
  - tbb==2021.5.0=h924138e_1
  - freetype==2.10.4=h0708190_1
  - ncurses==6.3=h27087fc_1
  - python[version='3.9.*,==3.9.13',build=h9a8a25e_0_cpython]

**Comment by frankassen** [comment]
Same problem here..

**Comment by alex-krull** [comment]
> Same problem here..

Thanks for your comment! Are you also using windows?

**Comment by frankassen** [comment]
Thanks for the prompt response!Indeed, also using windows.  Would love to try it out so hope it can be resolved :)On 01.08.2023, at 13:24, Alexander Krull ***@***.***> wrote:﻿

Same problem here..

Thanks for your comment! Are you also using windows?

**Comment by alex-krull** [comment]
We have only tested this on Linux so far. Have you tried to manually install pytorch, and pytorch lightning?

**Comment by bobfRT1** [comment]
Thanks Alex for your response!

Like this?

conda create -n GAP python=3.9    (I renamed the environment in the yml file to GAP)
conda activate GAP
conda install -c conda-forge pytorch-lightning

**(cuda 11.6 ?)**  conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge
conda env update --file GAP.yml --prune


Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ncurses==6.3=h27087fc_1
  - libstdcxx-ng==12.1.0=ha89aaad_16
  - pthread-stubs==0.4=h36c2ea0_1001
  - pillow==9.2.0=py39hae2aec6_0
  - _libgcc_mutex==0.1=conda_forge
  - readline==8.1.2=h0f457ee_0
  - numpy==1.22.3=py39he7a7128_0
  - openjpeg==2.4.0=hb52868f_1
  - pytorch==1.12.0=py3.9_cuda11.6_cudnn8.3.2_0
  - openh264==2.1.1=h780b84a_0
  - xorg-libxau==1.0.9=h7f98852_0
  - bzip2==1.0.8=h7f98852_4
  - zlib==1.2.12=h166bdaf_2
  - python[version='3.9.*,==3.9.13',build=h9a8a25e_0_cpython]
  - gmp==6.2.1=h58526e2_0
  - libiconv==1.17=h166bdaf_0
  - sqlite==3.39.1=h4ff8645_0
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - libwebp==1.2.2=h3452ae3_0
  - ld_impl_linux-64==2.36.1=hea4e1c9_2
  - jpeg==9e=h166bdaf_2
  - xz==5.2.5=h516909a_1
  - cudatoolkit==11.6.0=hecad31d_10
  - mkl_random==1.2.2=py39hde0f152_0
  - _openmp_mutex==4.5=2_kmp_llvm
  - libtiff==4.4.0=hc85c160_1
  - pysocks==1.7.1=py39hf3d152e_5
  - setuptools==63.2.0=py39hf3d152e_0
  - certifi==2022.6.15=py39hf3d152e_0
  - lz4-c==1.9.3=h9c3ff4c_1
  - cffi==1.15.1=py39he91dace_0
  - mkl-service==2.4.0=py39h7e14d7c_0
  - libxcb==1.13=h7f98852_1004
  - libnsl==2.0.0=h7f98852_0
  - cryptography==37.0.4=py39hd97740a_0
  - libuuid==2.32.1=h7f98852_1000
  - ca-certificates==2022.6.15=ha878542_0
  - libwebp-base==1.2.2=h7f98852_1
  - libffi==3.4.2=h7f98852_5
  - gnutls==3.6.13=h85f3911_1
  - libzlib==1.2.12=h166bdaf_2
  - mkl==2021.4.0=h8d4b97c_729
  - libgcc-ng==12.1.0=h8d9b700_16
  - freetype==2.10.4=h0708190_1
  - giflib==5.2.1=h36c2ea0_2
  - numpy-base==1.22.3=py39hf524024_0
  - ffmpeg==4.3=hf484d3e_0
  - llvm-openmp==14.0.4=he0ac6c6_0
  - nettle==3.6=he412f7d_0
  - brotlipy==0.7.0=py39hb9d737c_1004
  - lerc==3.0=h9c3ff4c_0
  - openssl==1.1.1q=h166bdaf_0
  - libdeflate==1.12=h166bdaf_0
  - tbb==2021.5.0=h924138e_1
  - libpng==1.6.37=h753d276_3
  - zstd==1.5.2=h8a70e8d_2
  - tk==8.6.12=h27826a3_0
  - lame==3.100=h7f98852_1001
  - mkl_fft==1.3.1=py39h0c7bc48_1


**with the exact hashes removed** 
 
conda env update --file GAP2.yml --prune

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libstdcxx-ng=12.1.0
  - _libgcc_mutex==0.1=conda_forge
  - ncurses=6.3
  - libuuid=2.32.1
  - nettle=3.6
  - libnsl=2.0.0
  - _openmp_mutex==4.5=2_kmp_llvm
  - ld_impl_linux-64=2.36.1
  - readline=8.1.2
  - gnutls=3.6.13
  - openh264=2.1.1
  - gmp
  - libgcc-ng=12.1.0

**Comment by alex-krull** [comment]
Have a look at his maybe: https://pytorch.org/get-started/locally/ I never tried this on windows before.

**Comment by bobfRT1** [comment]
[https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/)  is where  **_conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge_** came from :)

**Comment by alex-krull** [comment]
Sorry, bobfRT1. I am not sure how to best get pytorch running under windows. https://colab.google/ could be a way to try it on a linux system. Good luck! Let me know if you can make it work under windows.

**Comment by bobfRT1** [comment]
Sorry for not communicating precisely: I can install & run pytorch just fine. However, the yml file contains 100+ packages. Some of them are explicitly for linux and I have no way to tell what is actually needed to run GAP.

**Comment by alex-krull** [comment]
I am sorry, I currently don't have a windows machine to work how to best install the required software on windows. Have you tried to run the code after installing pytorch and pytorch lightning?

**Comment by bobfRT1** [comment]
I finally got the Train-and-Test.ipynb to run. I'll submit a pull request for a Win yml file.  Additionally, I had to remove
  **gpus = [0], devices = [0],**

from here:
trainer = pl.Trainer(default_root_dir=os.path.join(CHECKPOINT_PATH, name), gradient_clip_val=0.5,
                     **gpus = [0], devices = [0],**
                     max_epochs=maxepochs, 
                     callbacks=[ModelCheckpoint(save_weights_only=True, mode="min", monitor="val_loss"),
                                LearningRateMonitor("epoch"),
                                EarlyStopping('val_loss', patience=2000)])
